### Get all books
GET http://localhost:3000/books
Accept: application/json

### Find books by keyword
GET http://localhost:3000/books?keyword=Tolkien
Accept: application/json

### Find books paginated
GET http://localhost:3000/books?page=3
Accept: application/json

### Get book by id
GET http://localhost:3000/books/65fbfa0359608937e53a26cc
Accept: application/json

### Create new book
POST http://localhost:3000/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDU1YzZjYjA4N2Q0NDAxNWI5MTdiNCIsImlhdCI6MTcxMTYyODYwNCwiZXhwIjoxNzExODg3ODA0fQ.RweDsCb1dYwrvXlhtwwJua2IcxFQiw5UFIKlM8tSW9k

{
  "title": "Lord of the Rings",
  "description": "This is the description",
  "author": "J.R.R. Tolkien",
  "price": 100,
  "category": "fantasy"
}

### Update book
PUT http://localhost:3000/books/65fbfa0359608937e53a26cc
Content-Type: application/json

{
  "price": 36
}

### Delete book
DELETE http://localhost:3000/books/65fbf0a55e9c07483ed79a2d



