version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: school
    volumes:
      - ./data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

