name: coverage
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      statuses: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
#      - name: run test
#        run: npm run test
      - name: jest test with Coverage
        continue-on-error: true
        run: jest --coverage --coverageDirectory=. --json --outputFile=coverage-results.json

      - name: Process jest results with default
        if: always()
        uses: im-open/process-jest-test-results@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: coverage-results.json
