name: test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: jest-report
      url: https://viktorhreptovich.github.io/restapi-nestjs-mongodb/html-report-unit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: jest test
        run: npm run test
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html-report-unit
          path: html-report-unit
          retention-days: 1

  e2e-test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: jest-report
      url: https://viktorhreptovich.github.io/restapi-nestjs-mongodb/html-report-e2e
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: jest test
        run: npm run test:e2e
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html-report-e2e
          path: html-report-e2e
          retention-days: 1

  playwright-test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: playwright-report
      url: https://viktorhreptovich.github.io/restapi-nestjs-mongodb/playwright-report
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Build services
        run: docker compose -f test/playwright/docker/docker-compose-test.yml build
      - name: Playwright test
        run: npx playwright test
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 1


  deploy-reports:
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: [ unit-test, e2e-test, playwright-test ]
    if: always()
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: actions/download-artifact@v4
        with:
          path: reports
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          name: github-pages
          path: reports
      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: always()
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
        if: always()
